owner    = "kowainik"
fullName = "Kowainik"
email    = "xrom.xkov@gmail.com"
license  = "MPL-2.0"
lib      = true
test     = true
github   = true
travis   = true

ghcVersions = ["8.2.2", "8.4.4"]
stylish.url = "https://raw.githubusercontent.com/kowainik/org/master/.stylish-haskell.yaml"
contributing.url = "https://raw.githubusercontent.com/kowainik/org/master/CONTRIBUTING.md"

extensions = [ "ConstraintKinds"
             , "DeriveGeneric"
             , "GeneralizedNewtypeDeriving"
             , "InstanceSigs"
             , "KindSignatures"
             , "LambdaCase"
             , "OverloadedStrings"
             , "RecordWildCards"
             , "ScopedTypeVariables"
             , "StandaloneDeriving"
             , "TupleSections"
             , "TypeApplications"
             , "ViewPatterns"
             ]

[prelude]
    package = "relude"
    module  = "Relude"
